---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install apache2
    apt: name=apache2 state=present
  - name: start apache2
    service: name=apache2 state=started
  - name: install docker
    apt: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    apt: name=git state=present
  - name: clone a repo
    git: repo=https://github.com/AkshayP15/AnsibleDockerdemo.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t myadd:ansible2 .
  - name: create container
    command: docker run -itd -P myadd:ansible2
